{% set name = "simdutf" %}
{% set version = "5.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simdutf/simdutf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 86562dc31eda9681ecc4b7577a5c1f48e396e63f026674ef7b8d88752e634cf2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('simdutf', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $CONDA_PREFIX/include/simdutf.h  # [unix]
    - if not exist "%LIBRARY_INC%\simdutf.h" exit 1  # [win]

    - test -f $CONDA_PREFIX/lib/libsimdutf$SHLIB_EXT  # [unix]
    - if not exist "%LIBRARY_BIN%\simdutf.dll" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\simdutf.lib" exit 1  # [win]

about:
  home: https://github.com/simdutf/simdutf
  summary: 'Unicode at GB/s.'
  description: 'Unicode routines (UTF8, UTF16, UTF32): billions of characters per second using SSE2, AVX2, NEON, AVX-512.'
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  doc_url: https://simdutf.github.io/simdutf/
  dev_url: https://github.com/simdutf/simdutf

extra:
  recipe-maintainers:
    - pavelzw
    - simstoykov
