{% set name = "simdutf" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simdutf/simdutf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd24bab9754e24f42e6cd2c9d336accb2674c306f9221c00fb095fe95cfe9247

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('simdutf', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $CONDA_PREFIX/include/simdutf.h  # [unix]
    - if not exist "%LIBRARY_INC%\simdutf.h" exit 1  # [win]

    - test -f $CONDA_PREFIX/lib/libsimdutf$SHLIB_EXT  # [unix]
    - if not exist "%LIBRARY_BIN%\simdutf.dll" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\simdutf.lib" exit 1  # [win]

about:
  home: https://github.com/simdutf/simdutf
  summary: 'Unicode at GB/s.'
  description: 'Unicode routines (UTF8, UTF16, UTF32): billions of characters per second using SSE2, AVX2, NEON, AVX-512.'
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  doc_url: https://simdutf.github.io/simdutf/
  dev_url: https://github.com/simdutf/simdutf

extra:
  recipe-maintainers:
    - simstoykov
